version: '3'
services:
  controle-funcionarios:
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
        - ./:/var/www

  php:
    image: php:7.4-apache
    container_name: projeto-php
    ports:
      - "80:80"
      - "443:443"
    links:
      - postgres

  postgres:
    image: postgres
    container_name: projeto-postgres
    env_file:
      - .env

networks:
  funcionarios-network:
